apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Release.Name }}"
spec:
  secretName: "{{ .Release.Name }}-tls"
  dnsNames:
    - "{{ .Release.Name }}.{{ .Release.Namespace }}.svc"
    - "{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local"
  issuerRef:
    name: "{{ .Release.Name }}-selfsigned-issuer"
    kind: Issuer
