apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ .Release.Name }}"
webhooks:
  - name: "{{ .Release.Name }}.nais.io"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    matchPolicy: Equivalent
    reinvocationPolicy: IfNeeded
    clientConfig:
      service:
        name: "{{ .Release.Name }}"
        namespace: "{{ .Release.Namespace }}"
        path: /mutate
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
  - name: "{{ .Release.Name }}-hpa.nais.io"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    matchPolicy: Equivalent
    reinvocationPolicy: IfNeeded
    clientConfig:
      service:
        name: "{{ .Release.Name }}"
        namespace: "{{ .Release.Namespace }}"
        path: /mutate-hpa
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["autoscaling"]
        apiVersions: ["v1", "v2", "v2beta1", "v2beta2"]
        resources: ["horizontalpodautoscalers"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
  - name: "{{ .Release.Name }}-replicas.nais.io"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    matchPolicy: Equivalent
    reinvocationPolicy: IfNeeded
    clientConfig:
      service:
        name: "{{ .Release.Name }}"
        namespace: "{{ .Release.Namespace }}"
        path: /mutate-replicas
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
